// BRANDS
const BRAND = {
    GET_ALL:    'SELECT * FROM FN_GET_BRANDS();',
    GET_ALL_PAGED: 'FN_GET_BRANDS_PAGINATED',
    GET_ONE:    'FN_GET_BRAND',
    ADD:        'FN_ADD_BRAND',
    EDIT:       'FN_EDIT_BRAND',
    DELETE:     'FN_DEL_BRAND',
    ACTIVATE:   'FN_ACT_BRAND',
    DEACTIVATE: 'FN_DEACT_BRAND'
} as const;

// CATEGORIES
const CATEGORY = {
    GET_ALL:    'SELECT * FROM FN_GET_CATEGORIES();',
    GET_ALL_PAGED: 'FN_GET_CATEGORIES_PAGINATED',
    GET_ONE:    'FN_GET_CATEGORY',
    ADD:        'FN_ADD_CATEGORY',
    EDIT:       'FN_EDIT_CATEGORY',
    DELETE:     'FN_DEL_CATEGORY',
    ACTIVATE:   'FN_ACT_CATEGORY',
    DEACTIVATE: 'FN_DEACT_CATEGORY'
} as const;

// SUBCATEGORIES
const SUBCATEGORY = {
    GET_ALL:        'SELECT * FROM FN_GET_SUBCATEGORIES();',
    GET_ALL_PAGED: 'FN_GET_SUBCATEGORIES_PAGINATED',
    GET_ONE:        'FN_GET_SUBCATEGORY',
    ADD:            'FN_ADD_SUBCATEGORY',
    EDIT:           'FN_EDIT_SUBCATEGORY',
    DELETE:         'FN_DEL_SUBCATEGORY',
    ACTIVATE:       'FN_ACT_SUBCATEGORY',
    DEACTIVATE:     'FN_DEACT_SUBCATEGORY',
    WITH_SPECS:     'SELECT * FROM FN_GET_SUBCATEGORIES_WITH_SPECS();',
    WITHOUT_SPECS:  'SELECT * FROM FN_GET_SUBCAT_WITHOUT_SPECS();' 
} as const;

// PRODUCTS
const PRODUCT = {
    ADD:        'FN_ADD_PRODUCT',
    GET_ONE:    'FN_GET_PRODUCT', // new
    GET_ALL_PAGED: 'FN_GET_PRODUCTS_PAGINATED',
    ACTIVATE:   'FN_ACT_PRODUCT', 
    DEACTIVATE: 'FN_DEACT_PRODUCT'
} as const;

// VARIANTS
const VARIANT = {
    ADD:            'FN_ADD_VARIANT',               // VARIANTS
    DELETE:         'FN_DEL_VARIANT',               // VARIANTS
    ACTIVATE:       'FN_ACT_VARIANT',               // VARIANTS
    DEACTIVATE:     'FN_DEACT_VARIANT',             // VARIANTS
    EXISTS:         'SELECT FN_VARIANT_EXIST($1)',  // VARIANTS EXIST
    ADD_SPEC_VAL:   'FN_ADD_VARIANT_SPEC_VAL',      // VARIANTS SPECT VALUES
    DEL_SPEC_VAL:   'FN_DEL_VARIANT_SPEC_VAL',      // VARIANTS SPECT VALUES
    ACT_SPEC_VAL:   'FN_ACT_VARIANT_SPEC_VAL',      // VARIANTS SPECT VALUES
    DEACT_SPEC_VAL: 'FN_DEACT_VARIANT_SPEC_VAL'     // VARIANTS SPECT VALUES
} as const;

// SPECIFICATIONS
const SPECIFICATION = {
    ADD:        'FN_ADD_SPEC',      // SPECIFICATIONS
    ACTIVATE:   'FN_ACT_SPEC',      // SPECIFICATIONS
    DEACTIVATE: 'FN_DEACT_SPEC',    // SPECIFICATIONS
    ADD_VAL:    'FN_ADD_SPEC_VAL',  // SPECIFICATIONS VALUES
    ACT_VAL:    'FN_ACT_SPEC_VAL',  // SPECIFICATIONS VALUES
    DEACT_VAL:  'FN_DEACT_SPEC_VAL', // SPECIFICATIONS VALUES
    EXISTS:     'SELECT FN_SPEC_EXIST($1)',     // SPECIFICATIONS
    EXISTS_VAL: 'SELECT FN_SPEC_VAL_EXIST($1)'  // SPECIFICATIONS VALUES
} as const;

// PHOTOS
const PHOTO = {
    GET_NUMERATION: 'SELECT FN_GET_NUMERATION_PHOTO($1)',
    ADD_VAR:        'FN_ADD_PHOTO_VAR'
} as const;

// SEARCH
const SEARCH = {
    SPECS_SUBCAT:   '* FROM FN_SEARCH_SPECS_SUBCAT',
    SPECS_BRAND:    '* FROM FN_SEARCH_SPECS_BRAND',
    SPECS_PRODUCT:  '* FROM FN_SEARCH_SPECS_PRODUCT',

    SIZ_COL_SUBCAT:  '* FROM FN_GET_SIZ_COL_SUBCAT',
    SIZ_COL_BRAND:   '* FROM FN_GET_SIZ_COL_BRAND',
    SIZ_COL_PRODUCT: '* FROM FN_GET_SIZ_COL_PRODUCT',

    SIZ_SUBCAT:  '* FROM FN_GET_SIZ_SUBCAT',
    SIZ_BRAND:   '* FROM FN_GET_SIZ_BRAND',
    SIZ_PRODUCT: '* FROM FN_GET_SIZ_PRODUCT',

    COL_SUBCAT:  '* FROM FN_GET_COL_SUBCAT',
    COL_BRAND:   '* FROM FN_GET_COL_BRAND',
    COL_PRODUCT: '* FROM FN_GET_COL_PRODUCT',

    SPEC_SUBCAT:  '* FROM FN_GET_SPEC_SUBCAT',
    SPEC_BRAND:   '* FROM FN_GET_SPEC_BRAND',
    SPEC_PRODUCT: '* FROM FN_GET_SPEC_PRODUCT',

    VARIANTS_DETAILS_SUBCAT:  '* FROM FN_GET_VARIANTS_DETAILS_SUBCAT',
    VARIANTS_DETAILS_BRAND:   '* FROM FN_GET_VARIANTS_DETAILS_BRAND',
    VARIANTS_DETAILS_PRODUCT: '* FROM FN_GET_VARIANTS_DETAILS_PRODUCT',
} as const;

// USERS
const USER = {
    ADD_ADMIN:  'addUserAdmin',
    ADD_CLIENT: 'addUserClient',
    SIGNUP:     'signupUser',
    SIGNIN:     'SELECT * FROM signinUser($1)'
} as const;

// TOKENS
const TOKEN = {
    ADD_ADM:          'FN_ADD_REFRESH_TOKEN_ADM',
    ADD_CST:          'FN_ADD_REFRESH_TOKEN_CST',
    GET:              'FN_GET_REFRESH_TOKEN',
    REVOKE:           'FN_REVOKE_REFRESH_TOKEN',
    REVOKE_ALL_ADM:   'FN_REVOKE_ALL_TOKENS_ADM',
    REVOKE_ALL_CST:   'FN_REVOKE_ALL_TOKENS_CST',
    GET_ACTIVE_PAGED: 'FN_GET_LOGIN_ATTEMPTS_PAGINATED',
} as const;

// LOGIN ATTEMPTS
const LOGIN_ATTEMPT = {
    ADD: 'FN_ADD_LOGIN_ATTEMPT',
    GET_ALL_PAGED: 'FN_GET_LOGIN_ATTEMPTS_PAGINATED',
} as const;

// ADM USERS
const ADM_USER = {
    GET_BY_EMAIL:   'FN_GET_ADM_USER_BY_EMAIL',
    GET_BY_ID:      'FN_GET_ADM_USER_BY_ID',
    ADD:            'FN_ADD_ADM_USER',
    GET_ALL_PAGED:  'FN_GET_ADM_USERS_PAGINATED',
    TOGGLE_STATE:   'FN_TOGGLE_ADM_USER_STATE'
} as const;

// CST CUSTOMERS
const CST_USER = {
    GET_BY_EMAIL:   'FN_GET_CST_USER_BY_EMAIL',
    GET_BY_ID:      'FN_GET_CST_USER_BY_ID',
    ADD:            'FN_ADD_CST_USER',
    GET_ALL_PAGED:  'FN_GET_CST_USERS_PAGINATED',
    TOGGLE_STATE:   'FN_TOGGLE_CST_USER_STATE'
} as const;

const ADDRESS = {
    GET_BY_CUSTOMER: 'FN_GET_ADDRESSES_BY_CUSTOMER',
    GET_BY_ID:       'FN_GET_ADDRESS_BY_ID',
    ADD:             'FN_ADD_ADDRESS',
    EDIT:            'FN_EDIT_ADDRESS',
    DELETE:          'FN_DEL_ADDRESS',
    SET_DEFAULT:     'FN_SET_DEFAULT_ADDRESS'
} as const;

const COUNTRY = {
    GET_ALL: 'SELECT * FROM FN_GET_COUNTRIES();'
} as const;

export const QUERIES = {
    BRAND,
    CATEGORY,
    SUBCATEGORY,
    PRODUCT,
    VARIANT,
    SPECIFICATION,
    PHOTO,
    SEARCH,
    USER,   // faltan funciones de usuario, pero por ahora no se usan
    TOKEN,
    LOGIN_ATTEMPT,
    ADM_USER,
    CST_USER,
    ADDRESS,
    COUNTRY
} as const;